eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.96:8761/eureka/
spring:
  application:
    name: product-view-service-ribbon
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:      content-type: text/html
    mode: HTML5   