eureka:
  instance:
    hostname: 127.0.0.1
  client:
    ##集群的时候需要设置为true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
 
spring:
  application:
    name: eureka-server